# Generated by Django 5.0.6 on 2024-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
